### ISSUE TITLE
Multi-line snippets?

### ISSUE THREAD

**Issue by spapas** [dozius/keypirinha-snippets#3]
Are they supported? If yes how?

**Comment by dozius** [comment]
There is a [multi-line example](https://github.com/dozius/keypirinha-snippets/blob/3b0ddad7d3c9bf67c4f5e123d2802c5b89ec74e3/src/snippets.ini#L20) in the default configuration.

**Comment by spapas** [comment]
Thank you this wasn't in the release package I downloaded from https://github.com/dozius/keypirinha-snippets/releases

You may wish to upgrade that, kind regards!

**Comment by dozius** [comment]
Yes, you are right. I meant to get around to packaging a new release but completely forgot. Thanks for the reminder!
