### ISSUE TITLE
Different Categories for Snippets

### ISSUE THREAD

**Issue by mortyobnoxious** [dozius/keypirinha-snippets#4]
Hi, is it possible to have different categories for snippets,*

Just for the sake of example:

Category 1:
```
[main]
keyword = emojis

[snippet/😀]
string = 😀

[snippet/😐]
string = 😐
```

Category 2:
```
[main]
keyword = numbers

[snippet/80]
string = 80

[snippet/75]
string = 75
```

Category 3:
```
[main]
keyword = alphabet

[snippet/c]
string = c

[snippet/r]
string = r
```

**Comment by dozius** [comment]
This is currently not possible. Unfortunately, I'd have to basically re-write the entire plugin to support this. I'm open to a pull request, but it's very unlikely I will spend the time to implement this myself.

An alternative that would work with the current plugin would be to prefix the key values with category words and then you could easily filter items based on the prefix.

e.g.

```
[snippet/numbers_80]
string = 80

[snippet/numbers_75]
string = 75

[snippet/alphabet_c]
string = c

[snippet/alphabet_r]
string = r

... etc.
```

**Comment by mortyobnoxious** [comment]
Thank you, I will try that.
